### ISSUE TITLE
./include/hecate/hecate.hpp:48:10: fatal error: 'opencv2/ml.hpp' file not found

### ISSUE THREAD

**Issue by ganeshparameswaran** [yahoo/hecate#1]
On running make all:
> /*
>  * HECTATE Video Processing Library
>  *
>  * Copyright 2016 Yahoo Inc.
>  * Licensed under the terms of the Apache 2.0 License.
>  * See LICENSE file in the project root for terms.
>  *
>  * Developer: Yale Song (yalesong@yahoo-inc.com)
>  */
> 
> #ifndef HECATE_HPP
> #define HECATE_HPP
> 
> /ml.hpp
> LD -o .build_debug/lib/libhecate.so
> clang: warning: argument unused during compilation: '-pthread'
> CXX src/tools/hecate.cpp
> In file included from src/tools/hecate.cpp:11:
> ./include/hecate/hecate.hpp:48:10: fatal error: 'opencv2/ml.hpp' file not found

When I checked the include directory, I found that ml.hpp was in /usr/local/include/opencv2/ml/, so I hacked hecate.hpp to include opencv2/ml/ml.hpp and it worked. Any idea why?

**Comment by yalesong** [comment]
I think it has to do with different versions of OpenCV (which version are you using?). I am currently at NIPS, will check this next week when I'm back. Thanks!

**Comment by yalesong** [comment]
The problem seems to be solved, closing the issue.
