### ISSUE TITLE
Error while trying to generate GIF

### ISSUE THREAD

**Issue by ElectroBuddha** [yahoo/hecate#11]
Hi,
I get this error when trying to generate gifs:

sh: 1: -ss: not found
sh: 1: -ss: not found
rm: cannot remove './output//palatte.png': No such file or directory

Generating jpeg works fine.

**Comment by ElectroBuddha** [comment]
**Also cannot generate a summary video, receiving these errors:**

sh: 1: -ss: not found
mv: cannot stat './output/__tmp__video_01_seg000.mp4': No such file or directory
sh: 1: -i: not found
sh: 1: -ss: not found
mv: cannot stat './output/__tmp__video_01_seg001.mp4': No such file or directory
sh: 1: -i: not found
sh: 1: -f: not found


**And when trying to generate animated GIFs summary, receiving these errors:**

sh: 1: -ss: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory
sh: 1: -ss: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory
sh: 1: -ss: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory
sh: 1: -ss: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory
sh: 1: -ss: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory
sh: 1: -f: not found
sh: 1: -i: not found
sh: 1: -i: not found
rm: cannot remove './output//palatte.png': No such file or directory



**Only generating JPEGs is working without errors.**

**Comment by ElectroBuddha** [comment]
Sorry, it seems that FFMPEG was not properly installed on my linux machine. It's now working without problems. You can close this issue.

Best regards

**Comment by hyunsuk123** [comment]
@ElectroBuddha 
Could you please tell me how you solved the FFMPEG problem?
Did you just reinstall it or move FFMPEG folder to some other places?

Thank you
