### ISSUE TITLE
Fix for FFMPEG issue: The encoder 'aac' is experimental but experimental codecs are not enabled

### ISSUE THREAD

**Issue by ElectroBuddha** [yahoo/hecate#12]
Hi,
I have noticed that for some video clips, the Hecate won't generate 'gifsum' images, the tool returns message: 
`rm: cannot remove './output//palatte.png': No such file or directory`

After some quick debugging I've found that in those cases FFMPEG in the method 'ffmpeg_video_crop' produces error message:
`The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.`

The issue is fixed by editing 'include/hecate/ffmpeg_helper.hpp' file and changing the ffmpeg cmd string on the line 49 from:
`%s -ss %s -t %s -i %s -vf %s %s %s`
to
`%s -ss %s -t %s -i %s -strict -2 -vf %s %s %s`

Note that the placement of the '-strict -2' is important, it has to come after '-i' option.

**Comment by bjorn-ali-goransson** [comment]
Thanks for this!

**Comment by bjorn-ali-goransson** [comment]
Note: This has to be done everywhere `-i %s` is used in this file. I think OP only used some parts of this program so he didn't come across the other places.

**Comment by yalesong** [comment]
Thanks @ElectroBuddha and @bjorn-ali-goransson for this! I left the company so no longer has the write access to this repo. I create a PR on this so hope someone will merge it.

**Comment by Dumisanik** [comment]
The equivalent of adding the -strict experimental on the command line in to your C++ code is setting your codec context variable: strict_std_complaince to -2 before opening the codec.
AVCodecContext *c;
c->strict_std_compliance = -2;
/* open it */
ret = avcodec_open2(c, codec, NULL);
