### ISSUE TITLE
the aesthetic evaluation

### ISSUE THREAD

**Issue by leeqiaogithub** [yahoo/hecate#16]
I roughly read the source code and did not find any function about aesthetic evaluation.so I wonder if it is because i did not find it or you just did not achieve it.

**Comment by yalesong** [comment]
Not sure what you mean by aesthetic evaluation. If you are referring to Table 1 in our CIKM 2016 paper, you can find the code [here](https://github.com/yahoo/hecate/blob/master/include/hecate/image_metrics.hpp).

**Comment by leeqiaogithub** [comment]
@yalesong I mean what is mentioned in the paper about the supervised approach

**Comment by yalesong** [comment]
The code in my earlier comment computes aesthetic features. The Hecate library doesn't have training/inference code for the supervised approach (though it should be fairly straightforward to implement).

**Comment by leeqiaogithub** [comment]
@yalesong so the result of The Hecate Library only contain the results of unsupervised methods?

**Comment by yalesong** [comment]
Correct, the library implements only the unsupervised method from our CIKM 2016 paper. The supervised method didn't perform better than the unsupervised method, and computationally it's more involved (slow).

**Comment by leeqiaogithub** [comment]
well,thanks for your answer
