### ISSUE TITLE
no video result

### ISSUE THREAD

**Issue by leeqiaogithub** [yahoo/hecate#21]
when i run' ./distribute/bin/hecate -i examples/video.mp4 --generate_mov --lmov 15',there is no result in ./output.

**Comment by Domire** [comment]
modify the code:
generate_highlight_clips function : 
line:523 
`fprintf( ptr_filelist, "file %s%s_segAV%03d.mp4\n",
              cdot, filename.c_str(), shotid);`
to 
`fprintf( ptr_filelist, "file %s%s_segV%03d.mp4\n",
              cdot, filename.c_str(), shotid);`
