### ISSUE TITLE
Is there any way to monitor the processing progress?

### ISSUE THREAD

**Issue by vsyw** [yahoo/hecate#24]
Hi,  Thanks for the great library, just wondering if there is any way to monitor the progress while processing the video, thanks.

**Comment by vsyw** [comment]
@yalesong Do you have any idea on this? your reply will be much appreciate.

**Comment by yalesong** [comment]
Hi @iwantooxxoox, unfortunately the library doesn't support it at the moment. It should be fairly straightforward to implement it though, using a carriage return (\r) without a line-feed (\n). You are more than welcome to contribute!
