### ISSUE TITLE
Output quality is low?

### ISSUE THREAD

**Issue by arianaa30** [yahoo/hecate#25]
Interesting work. I compiled and was trying the video summarization, but noticed it reduces the output resolution/quality significantly. Any ways we can preserve the input resolution?

**Comment by yalesong** [comment]
Thanks! Yes, to preserve the original resolution you can specify `--mov_width_px -1`  (or `--jpg_width_px -1` or `--gif_width_px -1` depending on what your output format is). When the value is negative, it will copy the input resolution. See [these lines](https://github.com/yahoo/hecate/blob/master/include/hecate/hecate.hpp#L62-L64) in `include/hecate/hecate.hpp` and [these lines](https://github.com/yahoo/hecate/blob/master/src/hecate/hecate_main.cpp#L79-L91) in `src/hecate/hetace_main.cpp` for more information.

**Comment by arianaa30** [comment]
Great!
So right now the selection is based on "dynamism" score, right? Do you have any recent work or consider improving based on deep models to score "interestingness" or something?

**Comment by yalesong** [comment]
Some people have already tried incorporating deep nets to replace the scoring mechanism, reporting improved performance (I don't think they published a paper, but I know that version is deployed in production). I personally don't have an immediate plan to do so, unfortunately.
