### ISSUE TITLE
Code running speed

### ISSUE THREAD

**Issue by bellagao1023** [yahoo/hecate#26]
What is the configuration of the machine on which you run the code? I am running at a slower rate than mentioned in the paper.

**Comment by yalesong** [comment]
I moved to a different company a while ago and I no longer have access to the machine, nor do I remember its detailed specification/configuration. But I do remember that it used an MKL-enabled OpenCV. What's your runtime speed?

**Comment by bellagao1023** [comment]
It takes about 2 seconds to process a 14-second video.
