### ISSUE TITLE
opencv api multi-threading

### ISSUE THREAD

**Issue by bellagao1023** [yahoo/hecate#27]
I found that this code will open multi-threading when calling OpenCV api when running. How can I close it? Thank you very much.

**Comment by yalesong** [comment]
Could you provide more details? Do you mean there are dead threads not properly closed when the program terminates? What functionality were you using? If you can, can you find the line which opened the threads? I'd like to help with it's difficult to do so without these information.

**Comment by bellagao1023** [comment]
![1](https://user-images.githubusercontent.com/23240074/67536877-abc49980-f70b-11e9-94ec-74f85ab9f2b3.png)
When I run the code to extract the keyframes of many videos, I will check that the number of threads in the process will increase periodically and suddenly, and there are multiple threads in the sleep. Please find out which code will cause the number of threads to increase abruptly. Thank you very much.

**Comment by yalesong** [comment]
In general, `#pragma omp parallel for` will spawn multiple threads. Hope this helps.
