### ISSUE TITLE
Cannot build succesfully when using Opencv 4.1.2 + FFMPEG 4.2.1

### ISSUE THREAD

**Issue by SoumyashreeGad** [yahoo/hecate#29]
On executing make all

CXX src/hecate/hecate_highlight.cpp
/usr/bin/clang++ src/hecate/hecate_highlight.cpp -MMD -MP -pthread -fPIC -std=c++0x -DNDEBUG -O2 -I/usr/local/include/opencv4 -I.build_release/src -I./include -Wall -Wno-sign-compare -c -o .build_release/src/hecate/hecate_highlight.o 2> .build_release/src/hecate/hecate_highlight.o.warnings.txt \
		|| (cat .build_release/src/hecate/hecate_highlight.o.warnings.txt; exit 1)
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:39:
./include/hecate/gapstat.hpp:85:43: error: use of undeclared identifier 'CV_REDUCE_AVG'; did you mean 'REDUCE_AVG'?
          cv::reduce( km_data, km_ctr, 0, CV_REDUCE_AVG );
                                          ^~~~~~~~~~~~~
                                          REDUCE_AVG
/usr/local/include/opencv4/opencv2/core.hpp:220:20: note: 'REDUCE_AVG' declared here
                   REDUCE_AVG = 1, //!< the output is the mean vector of all rows/columns of the matrix.
                   ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:39:
./include/hecate/gapstat.hpp:89:44: error: use of undeclared identifier 'CV_TERMCRIT_ITER'
        TermCriteria km_opt = TermCriteria(CV_TERMCRIT_ITER|CV_TERMCRIT_EPS, km_max_cnt, km_eps);
                                           ^
./include/hecate/gapstat.hpp:89:61: error: use of undeclared identifier 'CV_TERMCRIT_EPS'
        TermCriteria km_opt = TermCriteria(CV_TERMCRIT_ITER|CV_TERMCRIT_EPS, km_max_cnt, km_eps);
                                                            ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:41:
./include/hecate/cc_parser.hpp:69:60: warning: 'bind1st<std::__1::not_equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
    dst.erase(dst.begin(), find_if(dst.begin(), dst.end(), bind1st(not_equal_to<char>(), ' ')));
                                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1053:1: note: 'bind1st<std::__1::not_equal_to<char>, char>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:41:
./include/hecate/cc_parser.hpp:70:49: warning: 'bind1st<std::__1::not_equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
    dst.erase(find_if(dst.rbegin(), dst.rend(), bind1st(not_equal_to<char>(), ' ')).base(), dst.end());
                                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1053:1: note: 'bind1st<std::__1::not_equal_to<char>, char>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:41:
./include/hecate/cc_parser.hpp:126:60: warning: 'bind1st<std::__1::not_equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
    dst.erase(dst.begin(), find_if(dst.begin(), dst.end(), bind1st(not_equal_to<char>(), ' ')));
                                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1053:1: note: 'bind1st<std::__1::not_equal_to<char>, char>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:41:
./include/hecate/cc_parser.hpp:127:49: warning: 'bind1st<std::__1::not_equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
    dst.erase(find_if(dst.rbegin(), dst.rend(), bind1st(not_equal_to<char>(), ' ')).base(), dst.end());
                                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1053:1: note: 'bind1st<std::__1::not_equal_to<char>, char>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:42:
./include/hecate/file_helper.hpp:78:72: warning: 'ptr_fun<int, int>' is deprecated [-Wdeprecated-declarations]
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<int, int>(std::isspace))));
                                                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1097:1: note: 'ptr_fun<int, int>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:42:
./include/hecate/file_helper.hpp:83:63: warning: 'ptr_fun<int, int>' is deprecated [-Wdeprecated-declarations]
    s.erase(std::find_if(s.rbegin(), s.rend(), std::not1(std::ptr_fun<int, int>(std::isspace))).base(), s.end());
                                                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1097:1: note: 'ptr_fun<int, int>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:43:
In file included from ./include/hecate/video_parser.hpp:46:
./include/hecate/hist_opencv.hpp:49:29: error: use of undeclared identifier 'CV_BGR2HSV'; did you mean 'COLOR_BGR2HSV'?
    cvtColor( img, img_cvt, CV_BGR2HSV );
                            ^~~~~~~~~~
                            COLOR_BGR2HSV
/usr/local/include/opencv4/opencv2/imgproc.hpp:583:5: note: 'COLOR_BGR2HSV' declared here
    COLOR_BGR2HSV      = 40, //!< convert RGB/BGR to HSV (hue saturation value), @ref color_convert_rgb_hsv "color conversions"
    ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:43:
In file included from ./include/hecate/video_parser.hpp:47:
./include/hecate/image_metrics.hpp:103:37: error: use of undeclared identifier 'CV_SORT_EVERY_COLUMN'; did you mean 'SORT_EVERY_COLUMN'?
      cv::sort( ghist, hist_sorted, CV_SORT_EVERY_COLUMN|CV_SORT_DESCENDING );
                                    ^~~~~~~~~~~~~~~~~~~~
                                    SORT_EVERY_COLUMN
/usr/local/include/opencv4/opencv2/core.hpp:155:18: note: 'SORT_EVERY_COLUMN' declared here
                 SORT_EVERY_COLUMN = 1, //!< each matrix column is sorted
                 ^
In file included from src/hecate/hecate_highlight.cpp:11:
In file included from ./include/hecate/hecate.hpp:43:
In file included from ./include/hecate/video_parser.hpp:47:
./include/hecate/image_metrics.hpp:103:58: error: use of undeclared identifier 'CV_SORT_DESCENDING'; did you mean 'SORT_DESCENDING'?
      cv::sort( ghist, hist_sorted, CV_SORT_EVERY_COLUMN|CV_SORT_DESCENDING );
                                                         ^~~~~~~~~~~~~~~~~~
                                                         SORT_DESCENDING
/usr/local/include/opencv4/opencv2/core.hpp:160:18: note: 'SORT_DESCENDING' declared here
                 SORT_DESCENDING   = 16 //!< each matrix row is sorted in the
                 ^
src/hecate/hecate_highlight.cpp:175:47: error: use of undeclared identifier 'CV_REDUCE_AVG'; did you mean 'REDUCE_AVG'?
    cv::reduce( Xsub, km_data.row(shotid), 0, CV_REDUCE_AVG );
                                              ^~~~~~~~~~~~~
                                              REDUCE_AVG
/usr/local/include/opencv4/opencv2/core.hpp:220:20: note: 'REDUCE_AVG' declared here
                   REDUCE_AVG = 1, //!< the output is the mean vector of all rows/columns of the matrix.
                   ^
src/hecate/hecate_highlight.cpp:444:23: error: use of undeclared identifier 'CV_CAP_PROP_FPS'; did you mean 'CAP_PROP_FPS'?
  double fps = vr.get(CV_CAP_PROP_FPS);
                      ^~~~~~~~~~~~~~~
                      CAP_PROP_FPS
/usr/local/include/opencv4/opencv2/videoio.hpp:137:8: note: 'CAP_PROP_FPS' declared here
       CAP_PROP_FPS            =5, //!< Frame rate.
       ^
6 warnings and 8 errors generated.
make: *** [.build_release/src/hecate/hecate_highlight.o] Error 1

**Comment by SoumyashreeGad** [comment]
Seems like the variables names have changes in open cv 4

**Comment by SoumyashreeGad** [comment]
I changed all the parameters which were renamed but then it threw an error:
```LD -o .build_release/lib/libhecate.so
Undefined symbols for architecture x86_64:
  "cv::VideoCapture::set(int, double)", referenced from:
      hecate::VideoParser::play_video_filtered(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) in video_parser.o
  "cv::VideoCapture::release()", referenced from:
      generate_highlight_clips(hecate_params&, std::__1::vector<hecate::Range, std::__1::allocator<hecate::Range> >&) in hecate_highlight.o
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
      hecate::VideoParser::play_video_filtered(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) in video_parser.o
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::VideoCapture::VideoCapture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      generate_highlight_clips(hecate_params&, std::__1::vector<hecate::Range, std::__1::allocator<hecate::Range> >&) in hecate_highlight.o
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
      hecate::VideoParser::play_video_filtered(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) in video_parser.o
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::VideoCapture::~VideoCapture()", referenced from:
      generate_highlight_clips(hecate_params&, std::__1::vector<hecate::Range, std::__1::allocator<hecate::Range> >&) in hecate_highlight.o
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
      hecate::VideoParser::play_video_filtered(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) in video_parser.o
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::VideoCapture::operator>>(cv::Mat&)", referenced from:
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
      hecate::VideoParser::play_video_filtered(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) in video_parser.o
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::imwrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::VideoCapture::get(int) const", referenced from:
      generate_highlight_clips(hecate_params&, std::__1::vector<hecate::Range, std::__1::allocator<hecate::Range> >&) in hecate_highlight.o
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
      generate_thumbnails(hecate_params&, std::__1::vector<int, std::__1::allocator<int> >&) in hecate_thumbnail.o
  "cv::VideoCapture::isOpened() const", referenced from:
      hecate::VideoParser::read_video(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, bool, int) in video_parser.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libhecate.so] Error 1```

**Comment by TriLoo** [comment]
have you solved this ld error ? I met same error building the code on MBP, and opencv version is 4.1

**Comment by TriLoo** [comment]
add opencv_imgcodecs, opencv_videoio can solve this `ld` error

**Comment by johnyoonh** [comment]
@yalesong would you able to take a look at this...?

**Comment by yalesong** [comment]
In general, when you see `ld: symbol(s) not found for architecture x86_64` it means libraries are not properly linked. You'd have to make sure `opencv_videoio` is properly linked to access functions related to video I/O, as @TriLoo mentioned above. 

BTW, sorry for the slow response -- I have moved to another company after released this code, and thus am no longer actively working on this project.
