### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by arianaa30** [yahoo/hecate#30]
Hi,
I was wondering if any documentation is available for the video summarization? Like, how do you generate the summary?

- One side question: I tested it to generate a 10s and 15s summary. I realized the 10s one is a subset of the 15s one. So wondering how the generation really works.

**Comment by arianaa30** [comment]
More specifically, can you provide a high-level definition of the way movie summarization works? Maybe at least these concepts:


```
segmenter: heuristic (seqlen=938 (15:952),nJumpsEst=15, nJumps=11, theta=0.25)
segmenter: heuristic (seqlen=213 (1628:1840),nJumpsEst=3, nJumps=2, theta=0.25)
segmenter: heuristic (seqlen=260 (1842:2101),nJumpsEst=4, nJumps=2, theta=0.25)
...
detect_highlight_shots(): min_shot_len=89, max_shot_len=89, min_num_shot=4, addrate_min=0.000000, addrate_max=0.000000
...
hecate: mov shot ranges:
range(11:99) (89) [24,68,83]
range(988:1095) (108) [1014,1034,1074,1119]
range(6073:6162) (90) [6069,6084,6104,6118,6133,6149,6154,6173]
```

**Comment by yalesong** [comment]
The documentation would be nice. Unfortunately, this repo is maintained by a single person (myself), and I am no longer at Yahoo anymore. I have moved on to different projects and I currently no longer have the capacity to invest time in this. Let me revisit this after there's enough interest in the community.
