### ISSUE TITLE
Possible license troubles

### ISSUE THREAD

**Issue by gerchicov-bp** [yahoo/hecate#32]
This library has appache license but uses another library with GPL.
If I plan to use this library then should my own project use GPL too?!

**Comment by yalesong** [comment]
@gyehuda, do you think you can handle this question?

**Comment by gyehuda** [comment]
@gerchicov-bp You are right to note that the code we published is licensed under Apache 2.0. You can use this code in combination with other code, such as OpenCV, FFMPEG, or anything else you add. Those projects are licensed differently (3-clause BSD, LGPL, GPL, etc. depending on details). 

When you create something that combines this (Apache licensed) library with other code, you'll want to review all the licenses and work with your legal or open source team to make sure that you comply with the sum of all obligations (where this is relevant). We don't know what you are planning to do, but from the perspective of this project, we offer this code under a very permissive Apache license. You can add or remove any dependency to make this library meet your needs.

**Comment by yalesong** [comment]
Thanks @gyehuda! 

@gerchicov-bp  I am closing this but feel free to bring this up again if necessary.
