### ISSUE TITLE
output resolution fixed to low resolution (360x202)?

### ISSUE THREAD

**Issue by wivaku** [yahoo/hecate#4]
My source video: 
`Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 986 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)`

The summary video: 
`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 360x202 [SAR 404:405 DAR 16:9], 344 kb/s, 24.82 fps, 25.08 tbr, 12800 tbn, 50 tbc (default)`

The thumbnails: 360x204 

Can the output resolution be defined?

**Comment by yalesong** [comment]
You can set the output resolution via the option <code>--mov_width_px INTEGER</code>. In your case, if you wanted the output to be of same resolution as the input video, you could do either <code>--mov_width_px 960</code> or simply <code>--mov_width_px -1</code>, in which case the output will copy the resolution of the input.
