### ISSUE TITLE
input files that contain spaces cause errors

### ISSUE THREAD

**Issue by wivaku** [yahoo/hecate#5]
Successful: file without space
`./distribute/bin/hecate -i examples/video.mp4 --generate_mov --lmov 15`

Successful: file with space - thumbnails
`./distribute/bin/hecate -i examples/my\ video.mp4 --generate_jpg --njpg 3`

Error message: file with space - summary video (or animated GIFs)
`./distribute/bin/hecate -i examples/my\ video.mp4 --generate_mov --lmov 15`

```
mv: rename ./output/__tmp__my_video_seg000.mp4 to ./output/__tmp__my_video_segV000.mp4: No such file or directory
mv: rename ./output/__tmp__my_video_seg001.mp4 to ./output/__tmp__my_video_segV001.mp4: No such file or directory
mv: rename ./output/__tmp__my_video_seg002.mp4 to ./output/__tmp__my_video_segV002.mp4: No such file or directory
mv: rename ./output/__tmp__my_video_seg003.mp4 to ./output/__tmp__my_video_segV003.mp4: No such file or directory
mv: rename ./output/__tmp__my_video_seg004.mp4 to ./output/__tmp__my_video_segV004.mp4: No such file or directory
```

**Comment by yalesong** [comment]
I was able to reproduce the error. I haven't considered this case when implementing, will work on it soon. You are welcome to contribute, too! In the meantime, you could make sure the input has no space.

**Comment by yalesong** [comment]
Commit [0d6fa70](https://github.com/yahoo/hecate/commit/0d6fa708f16a903385ed04f533a02dd0a7f32834) fixes this bug. Thanks for your contribution!
