### ISSUE TITLE
Bad memory access

### ISSUE THREAD

**Issue by DatHuynh** [yahoo/hecate#6]
I try to run your algorithm through a short video (around 5 secs) to extract gif using the following command:

> ./distribute/bin/hecate -i media/video.mp4 --generate_gif --ngif 1 -o output

Then I get a terminated error. After debugging, I figure out it is because of bad memory access in the following line of code in file _hecate_highlight.cpp_ :

```
// Collect IDs & scores of the shots in the k-th cluster
      vector<int> v_tmp_shotid;
      vector<double> v_tmp_score;
      for(int shotid=0; shotid<km_lbl.rows; shotid++) {
        int lbl = km_lbl.at<int>(shotid);
        if( lbl==k ) {
          double val = shot_diff_avg.at<double>(shotid);
          if( val > best_val ) {
            best_range = v_candidates[shotid];
            best_val = val;
          }
          v_tmp_shotid.push_back( shotid );
          v_tmp_score.push_back( val );
        }
      }
```

The case is that **shotid** was out of range for **shot_diff_avg**. In my case, **shotid** = 300 (**km_lbl.rows** = 2000) while **shot_diff_avg.rows** = 1 and **shot_diff_avg.cols** = 1.

I think that the for loop should also be constrained by **v_candidates.size()** .

**Comment by yalesong** [comment]
Thanks for reporting this issue! Would you mind sharing your video file so that I can debug properly?

**Comment by DatHuynh** [comment]
It has figured out where the problem is. It is because of opencv kmean implementation that automatically considers the transpose of the matrix when there is only one data point (a row vector as input). This behavior is based on the assumption that the input of kmean contain more than 1 data points [link](http://docs.opencv.org/2.4/modules/core/doc/clustering.html).
You can replicate the error when the video only contain one shot. Therefore, input to the kmean (**perform_kmeans**) in **detect_highlight_shots** would perform weirdly. If you couldn't reproduce the error, feel free to contact me for the video.

**Comment by DatHuynh** [comment]
I have already created a pull request. Hope it can fix the issue.

**Comment by yalesong** [comment]
PR to be merged upon receiving a valid CLA. Thanks for your contribution!
